# Generated by Django 2.0.4 on 2018-05-03 10:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('key', models.CharField(max_length=128)),
                ('attempt', models.IntegerField(default=0)),
                ('expires', models.IntegerField(default=2)),
                ('last_sent_mail', models.DateTimeField(blank=True, null=True)),
                ('forced_expired', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=user.models.User.initial_username, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and .-_ only.', max_length=35, unique=True, validators=[user.validator.validate_check_blacklist, django.core.validators.RegexValidator(regex='^(?=.{3,50}$)(?![_.])(?!.*[_.]{2})(?=.*[a-z])[a-z0-9._]+(?<![_.])$')], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='emailactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
