# Generated by Django 2.0.4 on 2018-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180503_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='key',
            field=models.CharField(max_length=256),
        ),
    ]
