# Generated by Django 2.0.4 on 2018-05-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180503_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailactivation',
            old_name='activated',
            new_name='verified',
        ),
    ]
